### ISSUE TITLE
About t-SNE visualization for FB15k-237

### ISSUE THREAD

**Issue by chuanyang-Zheng** [otiliastr/coper#1]
Hi, I want to know where can I get the code for **FB15k-237 t-SNE implementation**? I want to visualize some datasets. Thank you very much.

**Comment by gstoica27** [comment]
Hi,

We actually used the [tensorflow embedding projector](https://projector.tensorflow.org/) to visualize our learned embeddings. 

All you'd need to do is download the learned relation embeddings along with the ordered relation list, and upload them to the projector. 

The relation embeddings can be extracted by indexing into your trained model, and the ordered relation list can be gotten from the "relations.txt" file that's automatically created when you load the data for the first time. 

Hope this helps!

**Comment by chuanyang-Zheng** [comment]
Thank you very much. Thank you for your reply. 👍
