### ISSUE TITLE
about Heatmap of pairwise cosine similarities between relation embeddings

### ISSUE THREAD

**Issue by junkangwu** [otiliastr/coper#2]
May I ask you about the implementation of the Heatmap of pairwise cosine similarities between relation embedding? I'd like to reproduce this procedure such as “type” assignment?

**Comment by otiliastr** [comment]
Hi,

If I understand correctly, you're referring to Figure 1 from the Appendix, is that right? For that figure, we annotated the "type" assignments manually. You can follow these steps:

1. Given the relation embeddings and names, we manually inspected the names and assigned them types ("city", "country", etc.). Depending on the dataset, you might be able to extract the type automatically from the relation name. 
2. Once you have the type assignments, you can reorder the embeddings so relations that have the same type are next to each other (that allows you to see those diagonal blocks).
3. Then you can use any library heatmap function (eg. from matplotlib or seaborn) and generate the heatmap without labels.
4. We manually annotated the types labels to the diagonal blocks on the figure using some external image processing tool.

Wish there was a more automated tool to this, but unfortunately it was a lot of manual work. Hope this helps!

**Comment by junkangwu** [comment]
Thanks a lot for your detailed explanation. 
1. By the way, What do you think of the heatmap on the FB15K-237 dataset? Because I think it is hard to assign them types.
2. Such a heatmap about relations could be used for Relation Similarity. I would like to ask whether relation similarity is necessarily related to the prediction effect of downstream tasks?

**Comment by otiliastr** [comment]
1. Actually for FB15K-237 the relations given in the dataset have names that look like this: "_/music/genre/artists_" or "_/award/award_nominee/award_nominations./award/award_nomination/nominated_for_". So you could use these names to find types at different levels of granularity. These are the relations we show in Fig. 2 in the Appendix. For the entities, they are given as Freebase ids, so they are not interpretable. But some people have tried to recover the entity names by matching these ids to Wikidata (see [here](https://github.com/villmow/datasets_knowledge_embedding)).

2. In our method, we don't use the relation similarity matrix directly, and don't assume anything about it. But relations that are similar could share information via the parameter generator network, so I would expect the method to benefit when groups of relations in the data are similar.

**Comment by junkangwu** [comment]
Thanks a lot!
Best
